apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true
